// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8g2q3dTyH23F-uOTxEX1jUxFXvnyTR2Q',
    appId: '1:166225428289:web:745cd1423d3a7a0410ebc0',
    messagingSenderId: '166225428289',
    projectId: 'shoply-d2e48',
    authDomain: 'shoply-d2e48.firebaseapp.com',
    storageBucket: 'shoply-d2e48.firebasestorage.app',
    measurementId: 'G-TG4G6CEY92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLUKPf5Gktj9-OERKeSzHqHdes489YyWY',
    appId: '1:166225428289:android:d2dfbc2cc1b3cb2f10ebc0',
    messagingSenderId: '166225428289',
    projectId: 'shoply-d2e48',
    storageBucket: 'shoply-d2e48.firebasestorage.app',
  );
}
