// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRN7Ruxtnf0IR3oOF86q4iN5tAnDx1Swk',
    appId: '1:225034669985:web:42778370517c2dc73485e0',
    messagingSenderId: '225034669985',
    projectId: 'shoply-fc76c',
    authDomain: 'shoply-fc76c.firebaseapp.com',
    storageBucket: 'shoply-fc76c.firebasestorage.app',
    measurementId: 'G-NN6580HPD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArA0n3gRNabM9fCfL5_hiFp5cYZ4E_eRk',
    appId: '1:225034669985:android:00d9ba3a72df1ace3485e0',
    messagingSenderId: '225034669985',
    projectId: 'shoply-fc76c',
    storageBucket: 'shoply-fc76c.firebasestorage.app',
  );

}